import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, mkdirSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Shared dev vault (sibling of this repo). Build output is copied here on
// every build so the plugin is available in Obsidian without manual copying.
const VAULT_PLUGIN_DIR = resolve(
  __dirname,
  "../folder-tag-sync-dev-vault/.obsidian/plugins/folder-tag-sync",
);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Post-build: copy main.js + manifest.json + styles.css into the shared vault.
// Non-fatal if the vault dir doesn't exist yet — just logs and continues.
const copyToVaultPlugin = {
  name: "copy-to-vault",
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length) return;
      try {
        mkdirSync(VAULT_PLUGIN_DIR, { recursive: true });
        copyFileSync("main.js", `${VAULT_PLUGIN_DIR}/main.js`);
        copyFileSync("manifest.json", `${VAULT_PLUGIN_DIR}/manifest.json`);
        if (existsSync("styles.css")) {
          copyFileSync("styles.css", `${VAULT_PLUGIN_DIR}/styles.css`);
        }
        console.log(`→ synced to ${VAULT_PLUGIN_DIR}`);
      } catch (err) {
        // Vault might not be set up yet; don't break the build
        console.warn(`[copy-to-vault] skipped: ${err.message}`);
      }
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins: [copyToVaultPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
  console.log("👀 Watching for changes... (syncing to ../folder-tag-sync-dev-vault/)");
}
